version: "3.7"

services: 
  chatgpt-lark:
    build:
      context: ./
      dockerfile: docker/callback.Dockerfile
    ports: 
      - 8000:8000
    container_name: chatgpt-lark
    volumes: 
      - ./logs:/home/works/program/logs
      - ./conf/online.conf:/home/works/program/conf/online.conf
    restart: always